baseURL = 'https://www.odinseye.cloud'
languageCode = 'en-us'
title = 'Odin'
theme = "ananke"
canonifyURLs = "true"
disable_share = "true"

sectionPagesMenu = "main"

enableRobotsTXT = true
paginate = 3

googleAnalytics = "G-KWNZJ4607L"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Tropical Cyclone Modeling"
  mainSections = ["posts", "announcements"]
  site_logo = "/img/godin_icon.png"
  favicon = "/img/godin_icon.png"
  env = "production"
  googleAdsense="ca-pub-2365307104378138"
  recent_copy="Latest"
  recent_hurricane_number=6
  recent_posts_number=3
  # featured_image="https://storage.googleapis.com/godin_hurricane_data/wilfred2020/latest/wilfred2020_100x100_2021-09-09T005900+0000.jpeg"
  custom_css = ["code.css"]