baseURL = 'https://www.odinseye.cloud'
languageCode = 'en-us'
title = 'Odin'
theme = "ananke"
canonifyURLs = "true"
disable_share = "true"

sectionPagesMenu = "main"

enableRobotsTXT = true
paginate = 3

googleAnalytics = "G-KWNZJ4607L"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Tropical Cyclone Modeling"
  mainSections = ["posts", "hurricane"]
  site_logo = "/img/godin_icon.png"
  favicon = "/img/godin_icon.png"
  env = "production"
  googleAdsense="ca-pub-2365307104378138"