baseURL = 'https://odin.cliftbar.site'
languageCode = 'en-us'
title = 'Odin'
theme = "ananke"
canonifyURLs = "true"
disable_share = "true"
[params]
    description = "Hurricane modeling tracking"
    mainSections = ["posts", "hurricane"]
    site_logo = "/img/godin_icon.png"