baseURL = 'https://odin.cliftbar.site'
languageCode = 'en-us'
title = 'Godin'
theme = "ananke"
canonifyURLs = "true"
disable_share = "true"
[params]
    description = "Hurricane modeling tracking"
    mainSections = ["posts", "hurricane"]