steps:
- name: gcr.io/cloud-builders/gsutil
  args: [ 'cp', 'gs://godin-bin/security/godin-cloud-build-sa.json', 'gcp-credentials.json' ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: "sh"
  args: ["-c", "docker run -e GHT=$$GHT -v /workspace/gcp-credentials.json:/workspace/gcp-credentials.json gcr.io/godin-324403/stormbuilder"]
  env:
    - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcp-credentials.json'
  secretEnv: [ 'GHT' ]
availableSecrets:
  secretManager:
    - versionName: projects/godin-324403/secrets/github-token/versions/latest
      env: 'GHT'
timeout: 3600s